# Generated by Django 5.0.6 on 2024-05-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOrder',
            new_name='Customer_Order',
        ),
    ]
