# Generated by Django 5.0.6 on 2024-05-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0002_rename_customerorder_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_app.customer'),
        ),
    ]
