# Generated by Django 5.0.6 on 2024-05-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0003_alter_customer_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_app.order')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_app.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vehicles',
            field=models.ManyToManyField(through='bike_app.Order_Detail', to='bike_app.vehicle'),
        ),
        migrations.DeleteModel(
            name='Customer_Order',
        ),
    ]
