# Generated by Django 5.0.6 on 2024-05-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0004_order_order_detail_order_vehicles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vehicles',
            new_name='order_details',
        ),
    ]
